#! /bin/bash

# $Id: makevf,v 1.1 1999/05/25 12:16:26 loreti Exp $

cp $TETEXDIR/texmf/fonts/vf/bh/lubright/hlh??t.vf .

for file in hlh??t.vf
  do base="${file%vf}"
  vftovp ${base}vf ${base}tfm ${base}vpl
done

to="hlor7t"; from="hlhr7t.vpl"; mft="hlcrima"
ck="$(grep CHECKSUM ${mft}.pl | cut -d" " -f3 | sed 's/)//')"
awk >tmp -f maketfm.awk -v infile1=$from -v infile2=${mft}.pl
awk >${to}.vpl -f makevf.awk -v infile=tmp \
    -v mft=$mft -v ck=$ck
vptovf ${to}.vpl ${to}.vf ${to}.tfm
rm tmp

to="hlob7t"; from="hlhb7t.vpl"; mft="hlcdima"
ck="$(grep CHECKSUM ${mft}.pl | cut -d" " -f3 | sed 's/)//')"
awk >tmp -f maketfm.awk -v infile1=$from -v infile2=${mft}.pl
awk >${to}.vpl -f makevf.awk -v infile=tmp \
    -v mft=$mft -v ck=$ck
vptovf ${to}.vpl ${to}.vf ${to}.tfm
rm tmp

to="hlor8t"; from="hlhr8t.vpl"; mft="hlcrima"
ck="$(grep CHECKSUM ${mft}.pl | cut -d" " -f3 | sed 's/)//')"
awk >tmp -f maketfm.awk -v infile1=$from -v infile2=${mft}.pl
awk >${to}.vpl -f makevf.awk -v infile=tmp \
    -v mft=$mft -v ck=$ck
vptovf ${to}.vpl ${to}.vf ${to}.tfm
rm tmp

to="hlob8t"; from="hlhb8t.vpl"; mft="hlcdima"
ck="$(grep CHECKSUM ${mft}.pl | cut -d" " -f3 | sed 's/)//')"
awk >tmp -f maketfm.awk -v infile1=$from -v infile2=${mft}.pl
awk >${to}.vpl -f makevf.awk -v infile=tmp \
    -v mft=$mft -v ck=$ck
vptovf ${to}.vpl ${to}.vf ${to}.tfm
rm tmp *.pl *.vpl hlh*.tfm hlh*.vf
