#! /bin/bash

# $Id: maketfm,v 1.1 1999/05/25 12:16:26 loreti Exp $

cp $TETEXDIR/texmf/fonts/tfm/bh/lubright/hlh??t.tfm .
cp $TETEXDIR/texmf/fonts/tfm/bh/lumath/hlc?im*.tfm .

for file in *.tfm
  do tftopl $file ${file%tfm}pl
done

awk >hlor7t.pl -f maketfm.awk \
    -v infile1=hlhr7t.pl -v infile2=hlcrima.pl
awk >hlob7t.pl -f maketfm.awk \
    -v infile1=hlhb7t.pl -v infile2=hlcdima.pl
awk >hlor8t.pl -f maketfm.awk \
    -v infile1=hlhr8t.pl -v infile2=hlcrima.pl
awk >hlob8t.pl -f maketfm.awk \
    -v infile1=hlhb8t.pl -v infile2=hlcdima.pl

pltotf hlor7t.pl hlor7t.tfm
pltotf hlob7t.pl hlob7t.tfm
pltotf hlor8t.pl hlor8t.tfm
pltotf hlob8t.pl hlob8t.tfm

rm hl???t.pl hlc?im*.tfm
