#! /bin/bash

# $Id: makefd,v 1.1 1999/05/25 12:16:26 loreti Exp $

cp $TETEXDIR/texmf/tex/latex/lucidabr/*t1hlh.fd .

for infile in *.fd
  do outfile="${infile%h.fd}os.fd"
  awk >$outfile -f makefd.awk -v infile=$infile
done

rm *t1hlh.fd
