#!/bin/sh
rm -f  *.toc
rm -f  *.dvi
rm -f  *.cfg
latex newlfm.ins
rm -f  *.cfg
latex newlfm.dtx
latex newlfm.dtx
pdflatex newlfm.dtx
dvips -o newlfm.ps -l 24 newlfm
rm -f  *.toc
cp newlfm.dvi manual.dvi
cp newlfm.ps manual.ps
ps2pdf manual.ps manual.pdf
cp palm.eps palmb.eps
cp palm.pdf palmb.pdf
dvips -o newlfm.ps newlfm
rm -f  *.cfg
latex test1
latex test1
pdflatex test1
dvips -o test1.ps test1
rm -f  *.cfg
rm -f  *.cfg
latex test2
latex test2
pdflatex test2
dvips -o test2.ps test2  
rm -f  *.cfg
rm -f  *.cfg
latex test3
latex test3
pdflatex test3
dvips -o test3.ps test3
rm -f  *.cfg
rm -f  *.cfg
latex test4
latex test4
pdflatex test4
dvips -o test4.ps test4
rm -f  *.cfg
rm -f  *.cfg
latex test5
latex test5
pdflatex test5
dvips -o test5.ps test5
rm -f  *.cfg
rm -f  *.cfg
latex test6
latex test6
pdflatex test6
dvips -o test6.ps test6
rm -f  *.cfg
rm -f  *.cfg
latex test7
latex test7
pdflatex test7
dvips -o test7.ps test7
rm -f  *.cfg
rm -f  *.cfg
latex test8
latex test8
pdflatex test8
dvips -o test8.ps test8
rm -f  *.cfg
rm -f  *.cfg
latex test9
latex test9
pdflatex test9
dvips -o test9.ps test9
rm -f  *.cfg
rm -f  *.cfg
latex test10
latex test10
pdflatex test10
dvips -o test10.ps test10
rm -f  *.cfg
rm -f  *.cfg
latex test11
latex test11
pdflatex test11
dvips -o test11.ps test11
rm -f  *.cfg
rm -f  *.cfg
echo "                                                                          *"
echo "                                                                          *"
echo "***************************************************************************"
echo "***************************************************************************"
echo "make_unix has finished.                                                   *"
echo "                                                                          *"
echo "To determine success, check for existence of                              * "
echo "newlfm.cls setdim.sty addrset.sty                                         *"
echo "manual.ps newlfm.ps test1.ps - test8.ps                                   * "
echo "                                                                          *"
echo "To finish, move all files *.sty *.cls to the TeX path                     * "
echo "In addition, letrinfo.tex should go to the same place as newlfm.cls.      *"
echo "                                                                          *"
echo "They should go to the local path, not the package path                    *"
echo "                                                                          * "
echo "This ensures that upgrades to the package do not delete your              *"
echo "tailored version.                                                         * "
echo "                                                                          *"
echo "This file can be run as often as you wish.                                *"
echo "***************************************************************************"
echo "***************************************************************************"
echo "                                                                          *"
