#!/bin/sh
mv -f manual.ps manual.eps
rm -f  *.ps
mv -f manual.eps manual.ps
cp wine.pdf wine.xpdf
cp draft.pdf draft.xpdf
cp palm.pdf palm.xpdf
cp lvb.pdf lvb.xpdf
rm -f  test*.pdf
cp wine.xpdf wine.pdf
cp draft.xpdf draft.pdf
cp palm.xpdf palm.pdf
cp lvb.xpdf lvb.pdf
rm -f palmb.*
rm -f  *.dvi
rm -f  *.toc
rm -f  *.log
rm -f  *.aux
rm -f  *.idx
rm -f  *.glo
rm -f  *~
rm -f  *.cfg
rm -f  *#
rm -f  *.sty
rm -f  *.cls
