# fichier principal par défaut
@default_files = main;

# compilation via pdflatex uniquement
$pdf_mode = 1;
$pdflatex = 'pdflatex -synctex=1 %O %S';
#$dvi_mode = 0;

# génération de la bibliographie
#$bibtex = 2;

# génération de l'index avec fichier de style .ist
$makeindex = 'makeindex -s %B.ist %O -o %D %S';

# génération du glossaire
add_cus_dep('glo', 'gls', 0, 'run_makeglossaries');

sub run_makeglossaries {
  if ( $silent ) {
    system "makeglossaries -q '$_[0]'";
  }
  else {
    system "makeglossaries '$_[0]'";
  };
}

# fichiers temporaires additionnels à effacer
$clean_ext = "bbl bak backup %R-blx.bib run.xml ist gst synctex.gz";
$cleanup_includes_cusdep_generated = 1;
push @generated_exts, 'glo', 'gls', 'glg', 'glsdefs';

