#! /usr/bin/env bash

if [[ -n $( echo $* | egrep -- "-h\>|--help\>" ) ]]; then
    echo -e "Usage: $0 <myfile.tex>"
    echo "NB. \\input and \\include operations will only work in"
    echo "the current directory, rather than via the full TeX path."
    exit 0
fi

maintexfile=$1
tempfile=texmerge.$$

cat $maintexfile | sed -e s/'\\input{\([^}]*\)}'/'#include "\1\.tex"'/g > $tempfile
#cat $tempfile
cpp $tempfile 2> /dev/null | mail -s "generate bibtex" slaclib2@slac.stanford.edu
rm -f $tempfile
